name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
 
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
 
    env:
      Solution_Name: your-solution-name                         # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: your-test-project-path                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj. 
      OpenSlide_X86_Url: https://github.com/openslide/openslide-winbuild/releases/download/v20171122/openslide-win32-20171122.zip
      OpenSlide_X64_Url: https://github.com/openslide/openslide-winbuild/releases/download/v20171122/openslide-win64-20171122.zip
 
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Download openslide_win32.zip To Workspace
      # You may pin to the exact commit or the version.
      # uses: carlosperate/download-file-action@e85e0aa6262f13571d17a4a39687b26981c583dc
      uses: carlosperate/download-file-action@v1.0.3
      id: download-poetry
      with:
        # URL of the file to download
        file-url: 'https://github.com/openslide/openslide-winbuild/releases/download/v20171122/openslide-win32-20171122.zip'
        # New filename to rename the downloaded file
        file-name: 'openslide_win32.zip'
        
    - name: Print the file path
      run: echo "The file was downloaded to ${{ steps.download-poetry.outputs.file-path }}"
        
    - name: Extract openslide_win32.zip
      # You may pin to the exact commit or the version.
      # uses: DuckSoft/extract-7z-action@6eaaa506b410f047eaa9b22498696aad1e19a834
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        # archive path to extract
        pathSource: openslide_win32.zip
        # path to place the extract
        pathTarget: openslide_win32
        
    - name: Copy openslide_win32 Directory
      # You may pin to the exact commit or the version.
      # uses: MadaraUchiha/copy-action@7ddff6fc153a2ea2cd0fb88ed9750544c051e399
      uses: MadaraUchiha/copy-action@0.0.1
      with:
        # Source file
        source: openslide_win32/bin/
        # Target file
        target: openslide/x86/
 
    - name: Download openslide_win64.zip To Workspace
      # You may pin to the exact commit or the version.
      # uses: carlosperate/download-file-action@e85e0aa6262f13571d17a4a39687b26981c583dc
      uses: carlosperate/download-file-action@v1.0.3
      with:
        # URL of the file to download
        file-url: '$env:OpenSlide_X64_Url'
        # New filename to rename the downloaded file
        file-name: 'openslide_win64.zip'
        
    - name: Extract openslide_win64.zip
      # You may pin to the exact commit or the version.
      # uses: DuckSoft/extract-7z-action@6eaaa506b410f047eaa9b22498696aad1e19a834
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        # archive path to extract
        pathSource: openslide_win64.zip
        # path to place the extract
        pathTarget: openslide_win64
            
    - name: Copy openslide_win64 Directory
      # You may pin to the exact commit or the version.
      # uses: MadaraUchiha/copy-action@7ddff6fc153a2ea2cd0fb88ed9750544c051e399
      uses: MadaraUchiha/copy-action@0.0.1
      with:
        # Source file
        source: openslide_win64/bin/
        # Target file
        target: openslide/x64/
    - name: PowerShell script
      # You may pin to the exact commit or the version.
     # uses: Amadevus/pwsh-script@1f1751bbf3d1a92127bfc6c32403283625880cbf
      uses: Amadevus/pwsh-script@v2.0.1
      with:
        # PowerShell script to execute in Actions-hydrated context
        script: ls
